import turtle
import math


def draw_house():
    screen = turtle.Screen()
    screen.bgcolor("#87CEEB")
    screen.title("美丽的房子")
    screen.setup(800, 600)
    house_pen = turtle.Turtle()
    house_pen.speed(5)
    house_pen.pensize(3)
    house_pen.penup()
    house_pen.goto(-400, -200)
    house_pen.pendown()
    house_pen.color("#7CFC00")
    house_pen.begin_fill()
    for _ in range(2):
        house_pen.forward(800)
        house_pen.right(90)
        house_pen.forward(100)
        house_pen.right(90)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(-150, -100)
    house_pen.pendown()
    house_pen.color("#FFA500", "#FFA500")
    house_pen.begin_fill()
    for _ in range(4):
        house_pen.forward(300)
        house_pen.left(90)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(-150, 200)
    house_pen.pendown()
    house_pen.color("#8B0000", "#8B0000")
    house_pen.begin_fill()
    house_pen.goto(0, 300)
    house_pen.goto(150, 200)
    house_pen.goto(-150, 200)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(-50, -100)
    house_pen.pendown()
    house_pen.color("#8B4513", "#8B4513")
    house_pen.begin_fill()
    for _ in range(2):
        house_pen.forward(100)
        house_pen.left(90)
        house_pen.forward(150)
        house_pen.left(90)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(30, -50)
    house_pen.pendown()
    house_pen.color("#FFD700")
    house_pen.dot(10)
    house_pen.penup()
    house_pen.goto(-120, 50)
    house_pen.pendown()
    house_pen.color("#00BFFF", "#87CEEB")
    house_pen.begin_fill()
    for _ in range(4):
        house_pen.forward(70)
        house_pen.left(90)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(-85, 50)
    house_pen.pendown()
    house_pen.color("#FFFFFF")
    house_pen.forward(70)
    house_pen.penup()
    house_pen.goto(-120, 85)
    house_pen.pendown()
    house_pen.left(90)
    house_pen.forward(70)
    house_pen.penup()
    house_pen.goto(50, 50)
    house_pen.pendown()
    house_pen.right(90)
    house_pen.color("#00BFFF", "#87CEEB")
    house_pen.begin_fill()
    for _ in range(4):
        house_pen.forward(70)
        house_pen.left(90)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(85, 50)
    house_pen.pendown()
    house_pen.color("#FFFFFF")
    house_pen.forward(70)
    house_pen.penup()
    house_pen.goto(50, 85)
    house_pen.pendown()
    house_pen.left(90)
    house_pen.forward(70)
    house_pen.penup()
    house_pen.goto(80, 220)
    house_pen.pendown()
    house_pen.color("#696969", "#696969")
    house_pen.begin_fill()
    house_pen.right(90)
    for _ in range(2):
        house_pen.forward(80)
        house_pen.left(90)
        house_pen.forward(40)
        house_pen.left(90)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(70, 300)
    house_pen.pendown()
    house_pen.color("#8B0000", "#8B0000")
    house_pen.begin_fill()
    for _ in range(2):
        house_pen.forward(20)
        house_pen.left(90)
        house_pen.forward(60)
        house_pen.left(90)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(250, 200)
    house_pen.pendown()
    house_pen.color("#FFD700", "#FFD700")
    house_pen.begin_fill()
    house_pen.circle(40)
    house_pen.end_fill()
    house_pen.penup()
    house_pen.goto(-250, 200)
    house_pen.pendown()
    house_pen.color("#FFFFFF", "#FFFFFF")
    house_pen.begin_fill()
    house_pen.circle(30)
    house_pen.end_fill()

    house_pen.penup()
    house_pen.goto(-220, 220)
    house_pen.pendown()
    house_pen.begin_fill()
    house_pen.circle(30)
    house_pen.end_fill()

    house_pen.penup()
    house_pen.goto(-190, 200)
    house_pen.pendown()
    house_pen.begin_fill()
    house_pen.circle(30)
    house_pen.end_fill()

    house_pen.penup()
    house_pen.goto(150, 250)
    house_pen.pendown()
    house_pen.begin_fill()
    house_pen.circle(25)
    house_pen.end_fill()

    house_pen.penup()
    house_pen.goto(175, 265)
    house_pen.pendown()
    house_pen.begin_fill()
    house_pen.circle(25)
    house_pen.end_fill()

    house_pen.penup()
    house_pen.goto(200, 250)
    house_pen.pendown()
    house_pen.begin_fill()
    house_pen.circle(25)
    house_pen.end_fill()

    # 隐藏画笔
    house_pen.hideturtle()

    # 显示完成信息
    house_pen.penup()
    house_pen.goto(0, -250)
    house_pen.pendown()
    house_pen.color("#000000")
    house_pen.write("漂亮的家", align="center", font=("Arial", 24, "bold"))

    # 点击关闭窗口
    screen.exitonclick()


if __name__ == "__main__":
    draw_house()
